<a href="https://colab.research.google.com/github/Roopanshi-Marwaha/Bangalore_House_Price_Prediction/blob/main/Bangalore_House_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [506]:
import pandas as pd
import numpy as np

In [507]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("amitabhajoy/bengaluru-house-price-data")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'bengaluru-house-price-data' dataset.
Path to dataset files: /kaggle/input/bengaluru-house-price-data

In [508]:
import os
files_in_path = os.listdir(path)
print(files_in_path)

['Bengaluru_House_Data.csv']

In [509]:
data = pd.read_csv(path + "/Bengaluru_House_Data.csv")
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [510]:
data.shape

(13320, 9)

In [511]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [512]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
SLtalry     1
Rencyes     1
DiaveEn     1
Suiumy      1
Amionce     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
********************

In [513]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [514]:
data.drop(columns=['area_type','availability','society','balcony'],inplace=True)
#inplace=True ka matlab hai: change ko original DataFrame mein hi permanently apply karo, ek naya copy mat banao.
#Ye seedha data ko hi modify kar deta hai so koi naya variable banane ki zaroorat nahi padti, data khud updated ho jata hai (wo columns hamesha ke liye hat jate hain).

In [515]:
data.describe()
#by default only numeric columns come

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [516]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [517]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

#FILLING THE MISSING VALUES

###LOCATION

In [518]:
data['location'].value_counts()
#we have only 1 null value here
#so can fill anything won't affect

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [519]:
data['location']=data['location'].fillna('Sarjapur Road')

###SIZE

In [520]:
data['size'].value_counts()
#16 missing values were there so still less thus we are going to replace it with 2 BHK

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [521]:
data['size']=data['size'].fillna('2 BHK')

###Bath

In [522]:
data['bath']=data['bath'].fillna(data['bath'].median())
#73 missing values

In [523]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [524]:
data.isna().sum()
#no null values

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [525]:
data['bhk']=data['size'].str.split().str.get(0).astype(int)
#space se split karke first utha liya and then converted from string to int

In [526]:
data[data.bhk>20] #problem of outliers

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [527]:
data['total_sqft'].unique() #problem of range, there exits some ranges apart from float and int

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [528]:
def convertRange(x):
  temp=x.split('-')
  if len(temp)==2:
    return ((float(temp[0])+float(temp[1])/2))/2
  try:
    return float(x)
  except:
    return None

#split the range according to hyphen
#dono ko float mei convert karke then calc mean
#for nan values wr return none if float mei nahi hua convert
#nan values ko handle karne ke liye we have try and except

In [529]:
data['total_sqft']=data['total_sqft'].apply(convertRange)
#apply mei kisi function ka reference we need to pass
#har row ka sq feet we will get by this

In [530]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

###PRICE PER SQUARE FEET --> TO REMOVE OUTLIERS

In [531]:
#made new column
data['price_per_sqft']=data['price']*100000/data['total_sqft']
#multiplied as price in lakhs so decimal will be very big otherwise

In [532]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [533]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1551.811221      2.688814    112.565627      2.802778    7.937284e+03
std     1233.831436      1.338754    148.971674      1.294496    1.064293e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.277751e+03
50%     1270.000000      2.000000     72.000000      3.000000    5.482016e+03
75%     1675.000000      3.000000    120.000000      3.000000    7.357596e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [534]:
data['location'].value_counts()
#too much vakues-->so we can't pass this to the model

location
Whitefield                  540
Sarjapur  Road              399
Electronic City             302
Kanakpura Road              273
Thanisandra                 234
                           ...
Mango Garden Layout           1
Milk Colony                   1
Basnashankari,6th stage,      1
Near ullas theater            1
N R Layout                    1
Name: count, Length: 1306, dtype: int64

In [535]:
data['location']=data['location'].apply(lambda x: x.strip())
location_count=data['location'].value_counts()

#aage piche se space hat jayega as voh ek naya bana raha tha

In [536]:
location_count

location
Whitefield                541
Sarjapur  Road            399
Electronic City           304
Kanakpura Road            273
Thanisandra               237
                         ...
Xavier Layout               1
Ramanagara Channapatna      1
Maheswari Nagar             1
Hsr layout sector3          1
Thyagraj Nagar              1
Name: count, Length: 1295, dtype: int64

In [537]:
location_count_less_10=location_count[location_count<=10]
location_count_less_10

location
1st Block Koramangala     10
Dairy Circle              10
Nagadevanahalli           10
Sadashiva Nagar           10
Naganathapura             10
                          ..
Xavier Layout              1
Ramanagara Channapatna     1
Maheswari Nagar            1
Hsr layout sector3         1
Thyagraj Nagar             1
Name: count, Length: 1054, dtype: int64

In [538]:
data['location']=data['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)
#jinka count 10 se kaam hai they will be called others

In [539]:
data['location'].value_counts()

location
other                        2886
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

### OUTLIER DETECTION AND REMOVAL

In [540]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1551.811221      2.688814    112.565627      2.802778    7.937284e+03
std     1233.831436      1.338754    148.971674      1.294496    1.064293e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.277751e+03
50%     1270.000000      2.000000     72.000000      3.000000    5.482016e+03
75%     1675.000000      3.000000    120.000000      3.000000    7.357596e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [541]:
(data['total_sqft']/data['bhk']).describe()
#1 bhk mei kitne sq_feet hai
#1 sqft ka ghar kahan milta hai :)

count    13274.000000
mean       572.153732
std        387.483968
min          0.250000
25%        470.000000
50%        550.000000
75%        624.625000
max      26136.000000
dtype: float64

In [542]:
data=data[((data['total_sqft']/data['bhk'])>=300)]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12522.000000  12522.000000  12522.000000  12522.000000    12522.000000
mean    1586.879014      2.559815    111.428742      2.651014     6335.662717
std     1256.918220      1.078194    152.114556      0.976889     4167.659142
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1115.000000      2.000000     49.000000      2.000000     4225.281327
50%     1300.000000      2.000000     70.000000      3.000000     5330.765409
75%     1700.000000      3.000000    115.000000      3.000000     6969.451337
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [543]:
data.shape

(12522, 7)

In [544]:
data.price_per_sqft.describe()
#see max value-->outlier

count     12522.000000
mean       6335.662717
std        4167.659142
min         267.829813
25%        4225.281327
50%        5330.765409
75%        6969.451337
max      176470.588235
Name: price_per_sqft, dtype: float64

In [545]:
def remove_outliers_sqft(df):
  df_output=pd.DataFrame()
  for key,subdf in df.groupby('location'):
    m=np.mean(subdf.price_per_sqft)

    st=np.std(subdf.price_per_sqft)

    gen_df=subdf[(subdf.price_per_sqft>(m-st)) & (subdf.price_per_sqft<=(m+st))]
    df_output=pd.concat([df_output,gen_df],ignore_index=True)
  return df_output
data=remove_outliers_sqft(data)
data.describe()

#takes a dataframe of data
#then groupby by loaction --> we get key, subdf
#we calculated the mean and standard deviation
#the taking only that price jo mean se ek std idhar udhar ka ho and storing in gen_df
#concatinationg it to df_output
#then describe
#see the max now and notice the difference

         total_sqft          bath         price           bhk  price_per_sqft
count  10304.000000  10304.000000  10304.000000  10304.000000    10304.000000
mean    1501.302127      2.473991     91.307509      2.573467     5687.315133
std      874.020294      0.979110     86.237652      0.895728     2272.477140
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1105.000000      2.000000     49.000000      2.000000     4253.263769
50%     1280.500000      2.000000     67.000000      2.000000     5203.816132
75%     1650.000000      3.000000    100.000000      3.000000     6482.213439
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [546]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
    return df.drop(exclude_indices,axis='index')

    #making an array storing the indexes which we don't want --> to exclude
    #then groupby by location (loaction,subdataframe)--> for every loc
    #then bhk ke stats stored
    #then har loaction jo bhi ayegi (loc ka subdataframe) usko again grouby by bhk
    #then bhk_stats mei har bhk ke liye 3 cheeze store --> 1. mean-> bhk ka price per sqfeet ka mean 2. the uska std 3. the count karliya voh bhk kitni baar aya hai
    #agar mujhe 3bhk ka flat mila toh what is the lower bound of its price per sq feet? --> a valid lower bound will be isse kam value --> 2 bhk ka mean
    #so agar 3 bhk ka price_per_sq_feet>2 bhk ka mean then ham iss row ko rakh lenge
    #if we have suff enough data (>5) hoga toh we can accurately calc the mean
    #so, that's what we did in our code
    #we used get as value nahi milega toh loop chalega hi nahi otherwise if we simply write it, it will throw some error

In [547]:
data.shape # see reduced

(10304, 7)

In [548]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,1st Block Jayanagar,4 BHK,2850.0,4.0,428.00,4,15017.543860
1,1st Block Jayanagar,3 BHK,1630.0,3.0,194.00,3,11901.840491
2,1st Block Jayanagar,3 BHK,1875.0,2.0,235.00,3,12533.333333
3,1st Block Jayanagar,3 BHK,1200.0,2.0,130.00,3,10833.333333
4,1st Block Jayanagar,2 BHK,1235.0,2.0,148.00,2,11983.805668
...,...,...,...,...,...,...,...
10299,other,2 BHK,1353.0,2.0,110.00,2,8130.081301
10300,other,1 Bedroom,812.0,1.0,26.00,1,3201.970443
10301,other,3 BHK,1440.0,2.0,63.93,3,4439.583333
10302,other,2 BHK,1075.0,2.0,48.00,2,4465.116279
10303,other,4 BHK,3600.0,5.0,400.00,4,11111.111111

In [549]:
data.drop(columns=['size','price_per_sqft'],inplace=True)
#size kaam ka nahi tha
#price_per_sqft was only a feature to remove outlier so when removed remove it

In [550]:
data.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

##CLEANED DATA

In [551]:
data.to_csv("Cleaned_data.csv")